# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jose/workspace/Python/LiveScore/Vistas/mainWindow.ui'
#
# Created: Tue May  6 15:26:15 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 768)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../Recursos/iconos/ico.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tbCompeticion = QtGui.QTableWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbCompeticion.sizePolicy().hasHeightForWidth())
        self.tbCompeticion.setSizePolicy(sizePolicy)
        self.tbCompeticion.setMinimumSize(QtCore.QSize(350, 0))
        self.tbCompeticion.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tbCompeticion.setObjectName(_fromUtf8("tbCompeticion"))
        self.tbCompeticion.setColumnCount(4)
        self.tbCompeticion.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tbCompeticion.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbCompeticion.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbCompeticion.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbCompeticion.setHorizontalHeaderItem(3, item)
        self.tbCompeticion.horizontalHeader().setDefaultSectionSize(100)
        self.tbCompeticion.horizontalHeader().setMinimumSectionSize(20)
        self.tbCompeticion.horizontalHeader().setStretchLastSection(True)
        self.tbCompeticion.verticalHeader().setVisible(False)
        self.horizontalLayout_3.addWidget(self.tbCompeticion)
        self.tbJuegos = QtGui.QTableWidget(self.widget)
        self.tbJuegos.setObjectName(_fromUtf8("tbJuegos"))
        self.tbJuegos.setColumnCount(5)
        self.tbJuegos.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tbJuegos.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbJuegos.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbJuegos.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbJuegos.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tbJuegos.setHorizontalHeaderItem(4, item)
        self.tbJuegos.horizontalHeader().setCascadingSectionResizes(False)
        self.tbJuegos.horizontalHeader().setDefaultSectionSize(110)
        self.tbJuegos.horizontalHeader().setStretchLastSection(True)
        self.tbJuegos.verticalHeader().setCascadingSectionResizes(False)
        self.horizontalLayout_3.addWidget(self.tbJuegos)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setIconSize(QtCore.QSize(30, 30))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWConfig = QtGui.QDockWidget(MainWindow)
        self.dockWConfig.setEnabled(True)
        self.dockWConfig.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dockWConfig.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWConfig.setObjectName(_fromUtf8("dockWConfig"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.dockWidgetContents_3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents_3)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabConfGeneral = QtGui.QWidget()
        self.tabConfGeneral.setObjectName(_fromUtf8("tabConfGeneral"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabConfGeneral)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.tabConfGeneral)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_10)
        self.leditUrlIndex = QtGui.QLineEdit(self.groupBox_3)
        self.leditUrlIndex.setObjectName(_fromUtf8("leditUrlIndex"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.leditUrlIndex)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_11)
        self.leditUrlFlags = QtGui.QLineEdit(self.groupBox_3)
        self.leditUrlFlags.setObjectName(_fromUtf8("leditUrlFlags"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.leditUrlFlags)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.tabConfGeneral)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.groupBox_4)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_12 = QtGui.QLabel(self.groupBox_4)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_4.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_13)
        self.leditDirRecursos = QtGui.QLineEdit(self.groupBox_4)
        self.leditDirRecursos.setObjectName(_fromUtf8("leditDirRecursos"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.leditDirRecursos)
        self.leditDirFichConf = QtGui.QLineEdit(self.groupBox_4)
        self.leditDirFichConf.setObjectName(_fromUtf8("leditDirFichConf"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.leditDirFichConf)
        self.leditDirSalvaDatos = QtGui.QLineEdit(self.groupBox_4)
        self.leditDirSalvaDatos.setObjectName(_fromUtf8("leditDirSalvaDatos"))
        self.formLayout_4.setWidget(6, QtGui.QFormLayout.FieldRole, self.leditDirSalvaDatos)
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_14)
        self.gridLayout_2.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.tabConfGeneral)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_15 = QtGui.QLabel(self.groupBox_5)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 0, 0, 1, 1)
        self.leditTiempoAct = QtGui.QLineEdit(self.groupBox_5)
        self.leditTiempoAct.setObjectName(_fromUtf8("leditTiempoAct"))
        self.gridLayout.addWidget(self.leditTiempoAct, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(93, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_5, 2, 0, 1, 1)
        self.widget_4 = QtGui.QWidget(self.tabConfGeneral)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem1 = QtGui.QSpacerItem(106, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.btnCancelarInfGeneral = QtGui.QPushButton(self.widget_4)
        self.btnCancelarInfGeneral.setObjectName(_fromUtf8("btnCancelarInfGeneral"))
        self.horizontalLayout_6.addWidget(self.btnCancelarInfGeneral)
        self.btnGuardarInfGeneral = QtGui.QPushButton(self.widget_4)
        self.btnGuardarInfGeneral.setObjectName(_fromUtf8("btnGuardarInfGeneral"))
        self.horizontalLayout_6.addWidget(self.btnGuardarInfGeneral)
        self.gridLayout_2.addWidget(self.widget_4, 3, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tabConfGeneral, _fromUtf8(""))
        self.tabConfRed = QtGui.QWidget()
        self.tabConfRed.setObjectName(_fromUtf8("tabConfRed"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabConfRed)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.tabConfRed)
        self.groupBox.setCheckable(True)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.leditPxUser = QtGui.QLineEdit(self.groupBox)
        self.leditPxUser.setObjectName(_fromUtf8("leditPxUser"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.leditPxUser)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.leditPxPass = QtGui.QLineEdit(self.groupBox)
        self.leditPxPass.setEchoMode(QtGui.QLineEdit.Password)
        self.leditPxPass.setObjectName(_fromUtf8("leditPxPass"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.leditPxPass)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.leditPxHost = QtGui.QLineEdit(self.groupBox)
        self.leditPxHost.setObjectName(_fromUtf8("leditPxHost"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.leditPxHost)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.leditPxPort = QtGui.QLineEdit(self.groupBox)
        self.leditPxPort.setEchoMode(QtGui.QLineEdit.Normal)
        self.leditPxPort.setObjectName(_fromUtf8("leditPxPort"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.leditPxPort)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.widget_5 = QtGui.QWidget(self.tabConfRed)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem3 = QtGui.QSpacerItem(106, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.btnCancelarInfRed = QtGui.QPushButton(self.widget_5)
        self.btnCancelarInfRed.setObjectName(_fromUtf8("btnCancelarInfRed"))
        self.horizontalLayout_7.addWidget(self.btnCancelarInfRed)
        self.btnGuardarInfRed = QtGui.QPushButton(self.widget_5)
        self.btnGuardarInfRed.setObjectName(_fromUtf8("btnGuardarInfRed"))
        self.horizontalLayout_7.addWidget(self.btnGuardarInfRed)
        self.verticalLayout_3.addWidget(self.widget_5)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.tabWidget.addTab(self.tabConfRed, _fromUtf8(""))
        self.tabConfBD = QtGui.QWidget()
        self.tabConfBD.setObjectName(_fromUtf8("tabConfBD"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabConfBD)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_2 = QtGui.QGroupBox(self.tabConfBD)
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setChecked(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.leditBDName = QtGui.QLineEdit(self.groupBox_2)
        self.leditBDName.setObjectName(_fromUtf8("leditBDName"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.leditBDName)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.leditBDUser = QtGui.QLineEdit(self.groupBox_2)
        self.leditBDUser.setObjectName(_fromUtf8("leditBDUser"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.leditBDUser)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.leditBDPass = QtGui.QLineEdit(self.groupBox_2)
        self.leditBDPass.setObjectName(_fromUtf8("leditBDPass"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.leditBDPass)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.leditBDHost = QtGui.QLineEdit(self.groupBox_2)
        self.leditBDHost.setObjectName(_fromUtf8("leditBDHost"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.leditBDHost)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_8)
        self.leditBDPort = QtGui.QLineEdit(self.groupBox_2)
        self.leditBDPort.setObjectName(_fromUtf8("leditBDPort"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.leditBDPort)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.widget_6 = QtGui.QWidget(self.tabConfBD)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem5 = QtGui.QSpacerItem(106, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.btnCancelarInfBD = QtGui.QPushButton(self.widget_6)
        self.btnCancelarInfBD.setObjectName(_fromUtf8("btnCancelarInfBD"))
        self.horizontalLayout_8.addWidget(self.btnCancelarInfBD)
        self.btnGuardarInfBD = QtGui.QPushButton(self.widget_6)
        self.btnGuardarInfBD.setObjectName(_fromUtf8("btnGuardarInfBD"))
        self.horizontalLayout_8.addWidget(self.btnGuardarInfBD)
        self.verticalLayout_4.addWidget(self.widget_6)
        spacerItem6 = QtGui.QSpacerItem(20, 200, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.tabWidget.addTab(self.tabConfBD, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        self.dockWConfig.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWConfig)
        self.actionConfigurar = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../Recursos/iconos/Configure.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfigurar.setIcon(icon1)
        self.actionConfigurar.setObjectName(_fromUtf8("actionConfigurar"))
        self.actionDescargar = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../Recursos/iconos/Downloads Library.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDescargar.setIcon(icon2)
        self.actionDescargar.setObjectName(_fromUtf8("actionDescargar"))
        self.actionDetener = QtGui.QAction(MainWindow)
        self.actionDetener.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../Recursos/iconos/Power - Shut Down.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDetener.setIcon(icon3)
        self.actionDetener.setObjectName(_fromUtf8("actionDetener"))
        self.actionActualizar = QtGui.QAction(MainWindow)
        self.actionActualizar.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../Recursos/iconos/Power - Restart.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionActualizar.setIcon(icon4)
        self.actionActualizar.setObjectName(_fromUtf8("actionActualizar"))
        self.actionAyuda = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("../Recursos/iconos/Default.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAyuda.setIcon(icon5)
        self.actionAyuda.setObjectName(_fromUtf8("actionAyuda"))
        self.actionCrear_Archivo = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("../Recursos/iconos/Notepad.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCrear_Archivo.setIcon(icon6)
        self.actionCrear_Archivo.setObjectName(_fromUtf8("actionCrear_Archivo"))
        self.actionSalvar_Comp = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("../Recursos/iconos/Tasks.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSalvar_Comp.setIcon(icon7)
        self.actionSalvar_Comp.setObjectName(_fromUtf8("actionSalvar_Comp"))
        self.toolBar.addAction(self.actionDescargar)
        self.toolBar.addAction(self.actionCrear_Archivo)
        self.toolBar.addAction(self.actionSalvar_Comp)
        self.toolBar.addAction(self.actionConfigurar)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionActualizar)
        self.toolBar.addAction(self.actionDetener)
        self.toolBar.addAction(self.actionAyuda)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "LiveScore Futbol", None))
        item = self.tbCompeticion.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "País", None))
        item = self.tbCompeticion.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Competicion", None))
        item = self.tbCompeticion.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Traduccion", None))
        item = self.tbCompeticion.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "id", None))
        item = self.tbJuegos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hora", None))
        item = self.tbJuegos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tiempo", None))
        item = self.tbJuegos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Equipo", None))
        item = self.tbJuegos.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Resultado", None))
        item = self.tbJuegos.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Equipo", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.dockWConfig.setWindowTitle(_translate("MainWindow", "Configuración", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "URLs de Descarga", None))
        self.label_10.setText(_translate("MainWindow", "index", None))
        self.label_11.setText(_translate("MainWindow", "Banderas", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Directorios", None))
        self.label_12.setText(_translate("MainWindow", "Salvar Datos", None))
        self.label_13.setText(_translate("MainWindow", "Recursos", None))
        self.label_14.setText(_translate("MainWindow", "Fichero Conf.", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Actualizacion", None))
        self.label_15.setText(_translate("MainWindow", "Tiempo", None))
        self.btnCancelarInfGeneral.setText(_translate("MainWindow", "Cancelar", None))
        self.btnGuardarInfGeneral.setText(_translate("MainWindow", "Aceptar", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConfGeneral), _translate("MainWindow", "General", None))
        self.groupBox.setTitle(_translate("MainWindow", "Proxy", None))
        self.label.setText(_translate("MainWindow", "Usuario", None))
        self.label_2.setText(_translate("MainWindow", "Contraseña", None))
        self.label_3.setText(_translate("MainWindow", "host", None))
        self.label_4.setText(_translate("MainWindow", "Puerto", None))
        self.btnCancelarInfRed.setText(_translate("MainWindow", "Cancelar", None))
        self.btnGuardarInfRed.setText(_translate("MainWindow", "Aceptar", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConfRed), _translate("MainWindow", "Red", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Base de Datos", None))
        self.label_9.setText(_translate("MainWindow", "Nombre BD", None))
        self.label_6.setText(_translate("MainWindow", "Usuario", None))
        self.label_7.setText(_translate("MainWindow", "Contraseña", None))
        self.label_5.setText(_translate("MainWindow", "host", None))
        self.label_8.setText(_translate("MainWindow", "Puerto", None))
        self.btnCancelarInfBD.setText(_translate("MainWindow", "Cancelar", None))
        self.btnGuardarInfBD.setText(_translate("MainWindow", "Aceptar", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConfBD), _translate("MainWindow", "Almacenamiento", None))
        self.actionConfigurar.setText(_translate("MainWindow", "Configurar", None))
        self.actionConfigurar.setToolTip(_translate("MainWindow", "Configurar", None))
        self.actionDescargar.setText(_translate("MainWindow", "Descargar", None))
        self.actionDescargar.setToolTip(_translate("MainWindow", "Descargar", None))
        self.actionDetener.setText(_translate("MainWindow", "Detener", None))
        self.actionDetener.setToolTip(_translate("MainWindow", "Detener Actualizacion", None))
        self.actionActualizar.setText(_translate("MainWindow", "Actualizar", None))
        self.actionActualizar.setToolTip(_translate("MainWindow", "Actualizar", None))
        self.actionAyuda.setText(_translate("MainWindow", "Acerca de", None))
        self.actionAyuda.setToolTip(_translate("MainWindow", "Acerca de", None))
        self.actionCrear_Archivo.setText(_translate("MainWindow", "Crear Archivo", None))
        self.actionCrear_Archivo.setToolTip(_translate("MainWindow", "Crear Archivo", None))
        self.actionSalvar_Comp.setText(_translate("MainWindow", "Salvar Comp.", None))
        self.actionSalvar_Comp.setToolTip(_translate("MainWindow", "Salvar las competiciones que se van a mostrar", None))

